# 한국투자증권 API 설정
api:
  is_paper_trading: true                                   # 모의투자 여부 (true: 모의투자, false: 실전투자)
  
  # 실전투자 설정
  real:
    key: "PSoCplC0bjmBXIK1JV3DL42ojOCpm8NMCpkn"         # 실전투자 API Key
    secret: "2G0ITCDo/8zUgHgEnQci47qj4R5rMJkqWhC11Kqknwdp6yHXzK7WQpSrliJhlYJPyIn8zRFu1bZcEQ+Mbi10+ov3b6CkcqQU3et3HRnLh3uTQqAjGbaL13JAMcv67yuLX3M7362BqSF9iL773vG/tNx5Yh5yypc103I6Vu4TzIcz+RR9z7g="  # 실전투자 API Secret
    account: "7468442901"                                 # 실전투자 계좌번호
    url: "https://openapi.koreainvestment.com:9443"      # 실전투자 서버 주소
  
  # 모의투자 설정
  paper:
    key: "PSI6ckkJO8EJiSdIL99r51sTBtyrpCknXFfh"         # 모의투자 API Key
    secret: "gONKNcUXyEaBPCgmCFjX99p/KLTVg2sgsbloH+VnVIMr2YmxZw+1UKNiNwdsDFhBDTqgnThOKBcbCoSKue9NpzxW7wzSi+Tdp2Da8587+hLPDFRI5cBGCjqPRI2eEECOjZaNIMYZ9zWreU2OKZe9w9a8PG+BANTkwCCMn5/mdabEU68MErI="  # 모의투자 API Secret
    account: "5012496001"                                 # 모의투자 계좌번호
    url: "https://openapivts.koreainvestment.com:29443"  # 모의투자 서버 주소

# 디스코드 웹훅 설정
discord:
  webhook_url: "https://discord.com/api/webhooks/1335848253966778398/SLtYvQNqca_tL-OdLoKTwPYYZIRVHkeT2vAeerInYN0RGCzTQ-itRrmOZETlAYS6F1Mf"  # 디스코드 알림 웹훅 URL

# 구글 스프레드시트 설정
google_sheet:
  spreadsheet_id: "1HMg-EpaE1E19m3gZPpid0JZoJr_LAy2aEscyzB8MA9Q"  # 구글 스프레드시트 ID
  credentials_path: 'config/google_credentials.json'                # 구글 API 인증 파일 경로
  sheets:
    settings_kr: "투자설정[KOR]"    # 국내 투자 설정 시트
    settings_us: "투자설정[USA]"    # 미국 투자 설정 시트
    holdings_kr: "주식현황[KOR]"    # 국내 주식 현황 시트
    holdings_us: "주식현황[USA]"    # 미국 주식 현황 시트
  coordinates:
    # 투자설정 탭의 각 설정값 좌표 (국내/미국 공통)
    settings:
      max_individual_stocks: "G4"    # 최대 개별 종목 수
      max_pool_stocks: "G5"          # 최대 POOL 종목 수
      # 국내 시장 설정
      buy_time: "G8"              # 국내 시장 매수 시간
      sell_time: "G9"             # 국내 시장 매도 시간
      # 미국 시장 설정
      market_open_ratio: "G8"     # 미국 시장 시가 매수 비율 (%)
      market_close_ratio: "G9"    # 미국 시장 종가 매수 비율 (%)
      # 공통 설정
      stop_loss: "G14"               # 스탑로스 설정값 (%)
      trailing_start: "G15"          # 트레일링 시작 설정값 (%)
      trailing_stop: "G16"           # 트레일링 스탑 설정값 (%)
      rebalancing_date: "G11"        # 리밸런싱 일자
      rebalancing_ratio: "G12"       # 리밸런싱 비율 (%)
      individual_stocks: "A21:G50"   # 개별 종목 목록 범위
      pool_stocks: "A61:G80"         # POOL 종목 목록 범위
    
    # 주식현황 탭의 각 항목 좌표 (국내/미국 공통)
    holdings:
      last_update: "B5"            # 마지막 업데이트 시간
      error_message: "B6"          # 에러 메시지
      stock_list: "A11:K40"        # 보유 종목 리스트 범위

# 매매 설정
trading:
  market:
    type: ['KOR']                    # 거래 시장 설정 (KOR: 한국, USA: 미국)  type: ['KOR', 'USA']
  kor_market_start: '0900'           # 한국 장 시작 시간 (HHMM)
  kor_market_end: '1530'             # 한국 장 종료 시간 (HHMM)
  usa_market_start: '0930'           # 미국 장 시작 시간 (미국 현지 시간, HHMM)
  usa_market_end: '1600'             # 미국 장 종료 시간 (미국 현지 시간, HHMM)

# 로깅 설정
logging:
  level: INFO                        # 로깅 레벨 (DEBUG/INFO/WARNING/ERROR/CRITICAL)
  file_path: "logs/trading.log"      # 로그 파일 경로 